version: '3.8'

services:
  api:
    image: xbognar/gymapi:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - CONNECTION_STRING=${CONNECTION_STRING}
      - JWT_KEY=${JWT_KEY}
      - LOGIN_USERNAME=${LOGIN_USERNAME}
      - LOGIN_PASSWORD=${LOGIN_PASSWORD}
    ports:
      - "80:8080"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

volumes:
  db_data:
